### ISSUE TITLE
No native build was found for platform=darwin arch=arm64

### ISSUE THREAD

**Issue by minchopm** [Level/classic-level#82]
I am working on Mac M1 chipset, after executing "prebuild-darwin-x64+arm64": "prebuildify -t 8.14.0 --napi --strip --arch x64+arm64", 
I got this error:
No native build was found for platform=darwin arch=arm64 runtime=node abi=111 uv=1 armv=8 libc=glibc node=19.8.1

**Comment by Tadeuchi** [comment]
Hi, I'm facing similar problem.
When running classic-level on next.js there is an error:
Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=108 uv=1 armv=8 libc=glibc node=18.14.0

**Comment by callicles** [comment]
I got the same issue with platform=darwin and arch=x64

**Comment by Jon-Biz** [comment]
> I got the same issue with platform=darwin and arch=x64

I'm getting this too.

**Comment by michel-kraemer** [comment]
I had the same problem and solved it by adding `serverExternalPackages` to my `next.config.ts`:

```js
const config: NextConfig = {
  ...
  serverExternalPackages: ["classic-level"],
  ...
}

export default config
```

See also:
https://nextjs.org/docs/app/api-reference/next-config-js/serverExternalPackages

Note that I'm using Next.js 15. If you're using an older version, this setting might be under `experimental` with a slightly different name. See here:
https://nextjs.org/docs/14/app/api-reference/next-config-js/serverComponentsExternalPackages

More information about externals:
https://webpack.js.org/configuration/externals/

**Comment by ShookLyngs** [comment]
Got the same issue with Next.js 15, but sadly, adding the `serverExternalPackages` option to `next.config.ts` didn’t resolve it for me, the error details is down below. I’d appreciate any help with this issue, thanks.

```
 Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=137 uv=1 armv=8 libc=glibc node=24.1.0 webpack=true
    loaded from: /Users/<path-to-project>/next-app/.next/server/vendor-chunks

    at (ssr)/./node_modules/.pnpm/classic-level@1.4.1/node_modules/classic-level/binding.js (.next/server/vendor-chunks/classic-level@1.4.1.js:19:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:43)
    at (ssr)/./node_modules/.pnpm/classic-level@1.4.1/node_modules/classic-level/index.js (.next/server/vendor-chunks/classic-level@1.4.1.js:41:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:43)
    at (ssr)/./node_modules/.pnpm/level@8.0.1/node_modules/level/index.js (.next/server/vendor-chunks/level@8.0.1.js:19:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:43)
    ...
```
